project:
  type: website
  output-dir: docs

website:
  title: "Andrés F. Ramírez-Mejía (BSc, MSc, PhD)"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - past_work.qmd
      - current_work.qmd

format:
  html:
    theme:
     light: flatly
     dark: darkly
    css: styles.css
    toc: true

editor: visual

