project:
  type: website
  output-dir: docs

website:
  title: "Andrés F. Ramírez-Mejía"
  favicon: favicon.ico
  search: true
  back-to-top-navigation: true
  page-footer:
    left: "© 2026 Andrés F. Ramírez-Mejía"
    center:
      - icon: envelope
        href: mailto:andresfeliper.mejia@gmail.com
      - icon: github
        href: https://github.com/andres-frm
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=5NIPofoAAAAJ&hl=es
      - text: "ORCID"
        href: https://orcid.org/0000-0002-1986-2458
  navbar:
    search: true
    right:
      - href: index.qmd
        text: About
      - cv.qmd
      - list_publications.qmd
      - current_work.qmd
      - blog_stats.qmd

format:
  html:
    lightbox: true
    theme:
     light: [flatly, styles.scss]
     dark: [darkly, styles-dark.scss]
    toc: true
    grid:
      body-width: 850px
    include-in-header:
      text: '<link rel="apple-touch-icon" href="apple-touch-icon.png">'


