project:
  type: website
  output-dir: docs

website:
  title: "Andrés F. Ramírez-Mejía (BSc, MSc, PhD)"
  search: true
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright: 2023 Design by A.F. Ramírez-Mejía" 
    center: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
  navbar:
    background: '#5D6D7E'
    search: true
    right:
      - href: index.qmd
        text: Home
      - cv.qmd
      - list_publications.qmd
      - current_work.qmd
      - blog_stats.qmd
      - gallery.qmd

format:
  html:
    mainfont: Times New Roman
    theme:
     light: flatly
     dark: darkly
    css: styles.css
    toc: true


