---
title: "Data and black boxes"
---
------------------------------
*Note: The Internet has plenty of outstanding sources and textbooks written in English addressing similar, if not the same, topics of this blog. Instead of continuing to saturate this market, I prefer to increase the volume of available information in a different language. Therefore, I only wrote the introduction of the blog in English, headers are in both English and Spanish, but the content is only provided in my mother language.*
-----------------------------

Back in ~2014, I remember myself struggling to analyze my data using [SPSS](https://en.wikipedia.org/wiki/SPSS), [PAST](https://en.wikipedia.org/wiki/Paleontological_Statistics), and plotting figures in [SigmaPlot](https://en.wikipedia.org/wiki/SigmaPlot). I was confused and worried by the *'abnormality'* of my data, praying to the old and the new gods for a *p-value<0.05*, without understanding coefficients, their uncertainty, and implications for my conclusions. A completely nonsense. As time went by, the conceptual and methodological *black boxes* got smaller ---I started coding and using GLM(M). Still, only when I got in touch with Bayesian statistics was when I felt a deeper understanding of statistics. Bayesian approach makes probability more intuitive, offers a unified conceptual framework for data analysis, is more flexible and powerful for fitting complex models. All this comes at the cost of higher computational demand and programming skills (nothing arcane), but it brings a deeper understanding of the machinery inside the *black box* you are using; it makes you freer! 

I use [RPubs](https://rpubs.com) for sharing and explaining to others and myself, how to fit statistical models and extract insights from data. The content is structured from the most basic statistical model (the mean, $\mu$) to the more complex ones (hierarchical or multilevel models). I also provide `R` programming tutorials (e.g. data and programming structures, functions, simulations, graphics, etc), and a miscellaneous section with random stuffs. 

I am responsible for all hits and misses. Feel free to contact me if you detect mistakes, misunderstandings, or ways to improve any section.

Hopefully, this will be helpful for someone.

¡Un abrazo!


### R programming

### Bayes statistics

:::{}

- [Distribuciones de probabilidad y ejemplos en `R`](https://rpubs.com/andresfeli/1109337)(*Probability distributions and examples in R*)

- [Introducción a los modelos lineales generalizados (GLM)](https://rpubs.com/andresfeli/1110655) (*Introduction to generalized linear models (GLM)*)

-   [Introducción a los modelos jerárquicos I](https://rpubs.com/andresfeli/modelosjerarquicos1) (*Introduction to hierarchical models I*)

:::

### Miscelaneus 


