---
title: "Current projects "
---

### Pollination service and blueberry production in Argentina

During the last five years my research has been focused on understanding how spatial patterns interact with farming practices to modulate the provision and contribution of pollination service to blueberries production. Specifically I studied (and continue studying):

:::{}
i. Mechanisms driving the effect of animal pollination on the fruit production, fruit quality and nutritional content.

ii. Optimal pollination thresholds to maximize blueberry production.

iii. Individual and population effectiveness of birds and insects pollinating blueberries.

iv. Cascading processes affecting pollination service, from landscape to farming area.  
:::
 
This work was part of [SURPASS2](https://bee-surpass.org), an international collaboration involving  cross-country studies pollinator monitoring, crop pollination service, invasive species and land cover mapping.


::: {.border}
*Selected publications (only those were I played a significant role)*

-   **Ramírez-Mejía A F**, Blendinger P, Woodcock B, Schmucki R, Escobar L, Morton R, Vieli L, Nunes-Silva P, Lomáscolo S, Morales C, Murúa M, Agostini K, & Chacoff N. *The step by step of pollination service in blueberry crops*. **Second round of revision:** *Journal of Applied Ecology*.

-   **Ramírez-Mejía A F**, Chacoff N, Lomáscolo S, Woodcock B, Schmucki R & Blendinger P. *Optimal pollination thresholds to maximize blueberry production*. **First round of revision:** *Agriculture Ecosystems and Environment*

-   Nunes-Silva Patrícia, **Ramírez-Mejía A F.**, Blochtein B, Ramos J, Agostini K, Vieli L, Santanna M, Raguse-Quadros M, Maureen M., Chacoff N P, Cavigliasso P, Blendinger P G., Domingos S. **(2023)**. *Blueberry: pollination and production in South America*. ISBN: 978-65-00-65347-2. DOI: <https://doi.org/10.5281/zenodo.7770381>.

-   **Ramírez-Mejía A F**, Lomáscolo S & Blendinger P. **(2023)** *Hummingbirds, honeybees, and wild insect pollinators affect yield and berry quality of blueberries depending on cultivar and farm's spatial context*. *Agriculture Ecosystems and Environment*. DOI: <https://doi.org/10.1016/j.agee.2022.108229>
:::


### A control systems for managing crop pollination service



Utilizando modelos computacionales planeo desarrollar un sistema de control que permita a los agricultores de arándano decidir cuántas colmenas usar dadas las características de sus cultivos. Contarles por qué y cómo hacerlo, será el objetivo de esta charla.

#### SURPASS

International collaboration [SURPASS2](https://bee-surpass.org)

### Citrus
