---
title: "Publications"
---

Feel free to contact me if you request a copy or have comments to any work.

:::{}
-   **Ramírez-Mejía A. F.**, Chacoff N., Cavigliasso P., Blendinger P. **(2024)**. How much is enough? Optimizing beehive stocking densities to maximize the production of a pollinator-dependent crop. *Ecological modelling*, vol 498: <https://doi.org/10.1016/j.ecolmodel.2024.110891>.
-   Monasterologo, M, **Ramírez-Mejía A. F.**, et al. **(2024)**. Animal pollination contributes to more than half of Citrus spp. production despite the species and cultivar. *Scientific reports*, vol 14, Article number: 22309.  <https://www.nature.com/articles/s41598-024-73591-6>.
-   Fontanarrosa G., Zarbá L., ... **Ramírez-Mejía A. F.** ... Piquer-Rodríguez M. **(2024)**. Over twenty years of publications in Ecology: Over-contribution of Women reveals a new dimension of gender bias. *PLOS ONE*.  <https://doi.org/10.1371/journal.pone.0307813>
-   **Ramírez-Mejía A F**, Chacoff N, Lomáscolo S, Woodcock B, Schmucki R & Blendinger P. **(2024)**. Optimal pollination thresholds to maximize blueberry production. *Agriculture Ecosystems and Environment* <https://doi.org/10.1016/j.agee.2024.108903>
-   **Ramírez-Mejía A F**, Blendinger P, Woodcock B, Schmucki R, Escobar L, Morton R, Vieli L, Nunes-Silva P, Lomáscolo S, Morales C, Murúa M, Agostini K, & Chacoff N. **(2023)**. Landscape structure and farming management interacts to modulate pollination supply and crop production in blueberries. *Journal of Applied Ecology*. DOI: <https://doi.org/10.1111/1365-2664.14553>
-   Nunes-Silva Patrícia, **Ramírez-Mejía A F.**, Blochtein B, Ramos J, Agostini K, Vieli L, Santanna M, Raguse-Quadros M, Maureen M., Chacoff N P, Cavigliasso P, Blendinger P G., Domingos S. **(2023)**. *Blueberry: pollination and production in South America*. ISBN: 978-65-00-65347-2. DOI: <https://doi.org/10.5281/zenodo.7770381>.
-   **Ramírez-Mejía A F**, Lomáscolo S & Blendinger P. **(2023)**. Hummingbirds, honeybees, and wild insect pollinators affect yield and berry quality of blueberries depending on cultivar and farm's spatial context. *Agriculture Ecosystems and Environment*. DOI: <https://doi.org/10.1016/j.agee.2022.108229>
-   Blendinger P G, Rojas T N, **Ramírez-Mejía A F**, Bender I M A, Lomáscolo S, Magro J, Núñez Montellano M G, Ruggera R A, Valoy M & Ordano M. **(2022)** Nutrient balance and energy-acquisition effectiveness: do birds adjust their fruit diet to achieve intake targets? *Functional Ecology*. DOI: <https://doi.org/10.1111/1365-2435.14164>
-   **Ramírez-Mejía A F**, Urbina-Cardona N, & Sánchez F. **(2022)**. *The interplay of spatial scale and landscape transformation moderates the abundance and intraspecific variation in the ecomorphological traits of a phyllostomid bat*. *Journal of Tropical Ecology*. 38(1), 31-38. DOI: [doi:10.1017/S026646742100047X](https://www.cambridge.org/core/journals/journal-of-tropical-ecology/article/abs/interplay-of-spatial-scale-and-landscape-transformation-modulates-the-abundance-and-intraspecific-variation-in-the-ecomorphological-traits-of-a-phyllostomid-bat/9FE42D071008B1715D61864F94998527)
-   **Ramírez-Mejía A F**, Echeverry-Galvis M A, & Sánchez F. **(2021)**. Activity and habitat use by understory birds in a native Andean forest and a eucalypt plantation. *Wilson Journal of Ornithology*. 132(3): 721-729. DOI: <https://doi.org/10.1676/19-54>
-   **Ramírez-Mejía A F**, Urbina-Cardona N, & Sánchez F. **(2020)** Functional diversity of phyllostomid bats in an urban-rural landscape: a scale-dependent analysis. *Biotropica*. 52(6): 1168-1182. DOI: <https://doi.org/10.1111/btp.12816>.
-   **Ramírez-Mejía A F**, & Sánchez F. **(2016)**. Activity patterns and habitat use of mammals in an Andean forest and a Eucalyptus reforestation in Colombia. *Hystrix, the Italian Journal of Mammalogy*, 27(2): 104-110. DOI: <http://doi.org/10.4404/hystrix-27.2-11319>.
-   **Ramírez-Mejía A F**, & Sánchez F. **(2015)**. Non-volant mammals in a protected area on the Central Andes of Colombia: new records for the Caldas department and the Chinchiná River basin. *Check List*, 11(2):1-6, Article 1582. DOI: <http://dx.doi.org/10.15560/11.2.1582>.
:::


### Articles under review

:::{}
-   **Ramírez-Mejía A. F.**, Mary De Aquino, Michael Castaño Díaz, Juliana Hinz Wolter, Henry S. Pollock, J. Patrick Kelley, Jeferson Vizentin-Bugoni & Corey E. Tarwater. Biotic and abiotic factors directly and indirectly impact the structure of non-trophic networks across a rainfall gradient. *Journal: Ecology*. **Role: first author**
:::

### Manuscript in preparation

:::{}
-   Kimberley Jordan ... **Ramírez-Mejía A. F.**..., Corey E. Tarwater. Testing the space-for-time assumption: precipitation effects on avian body condition across scales. **Role: coauthor, data analysis**
-   **Ramírez-Mejía A. F.** Drivers of rarity and commonness in Neotropical bats: the role of the landscape, functional traits and intraspecific functional space. **Role: first author**
-   **Ramírez-Mejía A. F.**, A. Carolina Monmany, Roxana Aragón, Carolina Cuezzo, Natalia Ladino, Natalí Villalba, A. Carolina Jozami, Alberto Slanis, Mariano Lucia, Leopoldo Alvarez & Natacha P. Chacoff. Low opportunity cost areas in large-scale monoculture for pollinator conservatio. **Role: first author**
-   Ladino, N., **Ramírez-Mejía A. F.**, et al. Morphometrics as a tool for undestanding morphological variation and supporting taxonomic decisions in *Prionopelta* Mayr 1866 (Formicidae: Amblyoponinae). **Role: coauthor, data analysis**
-   Ladino, N., **Ramírez-Mejía A. F.**, et al. Optimizing measurement effort in taxonomic studies on Formicidae. **Role: coauthor, data analysis**
:::


### Code and online datasets

:::{}

-   **Ramírez-Mejía A. F.**, Chacoff N., Cavigliasso P., & Blendinger P. (2024). How much is enough? Optimizing beehive stocking densities to maximize the production of a pollinator-dependent crop. *Ecological modelling*, vol 498, article number: <https://doi.org/10.1016/j.ecolmodel.2024.110891>. GitHub repository: <https://github.com/andres-frm/postdoc_cropPol>

-   **Ramírez-Mejía, Andrés F**. (2023). Landscape structure and farming management interacts to modulate pollination supply and crop production in blueberries [code]. **Journal of Applied Ecology**. Zenodo. <https://doi.org/10.5281/zenodo.10070657>

-   **Ramírez-Mejía, Andrés F**. et al. (2023). Landscape structure and farming management interacts to modulate pollination supply and crop production in blueberries [Dataset]. **Journal of Applied Ecology**. Dryad. <https://doi.org/10.5061/dryad.bg79cnphc>

-   **Ramírez-Mejía, A F**.; Urbina-Cardona, J N; Sánchez, F (2020). Data from: Functional diversity of phyllostomid bats in an urban-rural landscape: a scale-dependent analysis [Dataset]. **Biotropica**. Dryad. <https://doi.org/10.5061/dryad.sn02v6x1p>
:::


### Theses

:::{}
-   **PhD degree** --- (2018 - 2023). The step-by-step of pollination service in blueberry crops: patterns and mechanisms. Thesis advisors: [Dr Pedro G. Blendinger](https://scholar.google.com/citations?user=9oyNtX0AAAAJ&hl=en&oi=ao); independent research CONICET, assistant professor UNT. [Dr Silvia Lomáscolo](https://scholar.google.com/citations?hl=en&user=r9PAo-QAAAAJ); assistant researcher CONICET.

-   **Master's degree** --- (2015 - 2017) Seed dispersion and functional diversity of phyllostomid bats in an anthropogenic landscape: a multi-scale approach. Thesis advisors: [Dr Francisco Sánchez](https://scholar.google.com/citations?user=6MC0Yx8AAAAJ&hl=en); Universidad de los Llanos, Colombia. [Dr J. Nicolás Urbina-Cardona](https://scholar.google.com/citations?user=uMBjaFgAAAAJ&hl=en); Pontificia Universidad Javeriana, Colombia.

-   **Undergraduate** --- (2008 - 2014) Activity, habitat use and richness of mammals in native forest and eucalyptus reforestations in the Colombian Andes. Thesis advisor: [Dr Francisco Sánchez](https://scholar.google.com/citations?user=6MC0Yx8AAAAJ&hl=es); Universidad Militar Nueva Granada, Cundinamarca, Colombia.
:::
